BEGIN;

WITH mapping(old_name, new_name) AS (
  VALUES
    ('Barbell Bench Press', 'Langhantel Bankdruecken'),
    ('Incline Bench Press', 'Schraegbankdruecken'),
    ('Decline Bench Press', 'Negativbankdruecken'),
    ('Dumbbell Flat Press', 'Kurzhantel Flachbankdruecken'),
    ('Dumbbell Incline Press', 'Kurzhantel Schraegbankdruecken'),
    ('Machine Chest Press', 'Brustpresse Maschine'),
    ('Cable Fly', 'Kabel-Flys'),
    ('Pec Deck', 'Pec Deck'),
    ('Push Up', 'Liegestuetz'),
    ('Weighted Dip', 'Gewichtete Dips'),
    ('Overhead Press', 'Schulterdruecken'),
    ('Seated Dumbbell Shoulder Press', 'Sitzendes Kurzhantel-Schulterdruecken'),
    ('Lateral Raise', 'Seitheben'),
    ('Cable Lateral Raise', 'Kabel-Seitheben'),
    ('Rear Delt Fly', 'Reverse Fly Maschine'),
    ('Face Pull', 'Face Pull'),
    ('Upright Row', 'Aufrechtes Rudern'),
    ('Barbell Shrug', 'Langhantel Shrugs'),
    ('Dumbbell Shrug', 'Kurzhantel Shrugs'),
    ('Deadlift', 'Kreuzheben'),
    ('Romanian Deadlift', 'Rumaenisches Kreuzheben'),
    ('Stiff Leg Deadlift', 'Steifbeiniges Kreuzheben'),
    ('Good Morning', 'Good Mornings'),
    ('Pull Up', 'Klimmzug'),
    ('Assisted Pull Up', 'Unterstuetzter Klimmzug'),
    ('Chin Up', 'Untergriff-Klimmzug'),
    ('Lat Pulldown Wide', 'Latzug Breit'),
    ('Lat Pulldown Neutral', 'Latzug Neutral'),
    ('Seated Cable Row', 'Sitzendes Kabelrudern'),
    ('Barbell Row', 'Langhantelrudern'),
    ('T-Bar Row', 'T-Bar Rudern'),
    ('Chest Supported Row', 'Brustgestuetztes Rudern'),
    ('Single Arm Dumbbell Row', 'Einarmiges Kurzhantelrudern'),
    ('Straight Arm Pulldown', 'Gerader Armzug'),
    ('Barbell Squat', 'Langhantel Kniebeuge'),
    ('Front Squat', 'Frontkniebeuge'),
    ('Hack Squat', 'Hackenschmidt Kniebeuge'),
    ('Leg Press', 'Beinpresse'),
    ('Bulgarian Split Squat', 'Bulgarische Kniebeuge'),
    ('Walking Lunge', 'Gehende Ausfallschritte'),
    ('Step Up', 'Step-Ups'),
    ('Leg Extension', 'Beinstrecker'),
    ('Leg Curl', 'Beinbeuger'),
    ('Seated Leg Curl', 'Sitzender Beinbeuger'),
    ('Hip Thrust', 'Hip Thrust'),
    ('Glute Bridge', 'Glute Bridge'),
    ('Cable Kickback', 'Kabel-Kickbacks'),
    ('Standing Calf Raise', 'Wadenheben stehend'),
    ('Seated Calf Raise', 'Wadenheben sitzend'),
    ('Barbell Curl', 'Langhantelcurls'),
    ('EZ Bar Curl', 'SZ-Curls'),
    ('Dumbbell Curl', 'Kurzhantelcurls'),
    ('Hammer Curl', 'Hammercurls'),
    ('Preacher Curl', 'Preacher Curls'),
    ('Cable Curl', 'Kabelcurls'),
    ('Triceps Pushdown', 'Trizepsdruecken am Kabel'),
    ('Overhead Triceps Extension', 'Ueberkopf-Trizepsstrecken'),
    ('Skull Crusher', 'Skull Crusher'),
    ('Close Grip Bench Press', 'Enges Bankdruecken'),
    ('Rope Pushdown', 'Seil-Pushdown'),
    ('Crunch', 'Crunches'),
    ('Cable Crunch', 'Kabel-Crunches'),
    ('Plank', 'Plank'),
    ('Side Plank', 'Seitstuetz'),
    ('Hanging Leg Raise', 'Haengendes Beinheben'),
    ('Russian Twist', 'Russian Twist'),
    ('Back Extension', 'Rueckenstrecker'),
    ('Bird Dog', 'Bird Dog'),
    ('Band Pull Apart', 'Band Pull-Aparts'),
    ('Band Face Pull', 'Band Face Pull')
)
UPDATE public.training_exercises te
SET
  name = mapping.new_name,
  updated_at = NOW()
FROM mapping
WHERE te.is_system = TRUE
  AND te.name = mapping.old_name;

COMMIT;
